### ISSUE TITLE
support for shared and static build

### ISSUE THREAD

**Issue by SSE4** [AngryJayFox/ffmpeg-libs-makescript#5]
ffmpeg supports shared and static build
to build static, add the following two options to configure command: `--disable-shared --enable-static`
to build shared, add the following two options to configure command: `--disable-static --enable-shared`

add arguments to argparse : `--shared` and `--static` to build appropriate ffmpeg builds.
static build should be default options.

**Comment by AngryJayFox** [comment]
made
